export const Keys = Object.freeze({
  // Client ID
  CLIENT_ID: "Z1HSHTJQLY4XT3YXGXJJNPWUFPJHPZDUJAE3LMFKXUPS0UJ3",

  // Client Secret
  CLIENT_SECRET: "LYSNFZR5UBCE433BFKAHQXULOHRQYP1LEYQWBX5QHF5235ED"
});